import React, { useEffect } from 'react'
import styles from '@/styles/Login.module.css'
import Image from 'next/image'
import Head from 'next/head'
import Logincard from '@/public/components/logincard'
import { useRouter } from 'next/router'
import GLOBAL_CONSTANTS from '@/global_constants'

const login = () => {


    const router = useRouter()

    useEffect(() => {
      if (localStorage.getItem('token')) {
        router.push(`${GLOBAL_CONSTANTS.base_url}`)
      }
    }, [])
    

    return (
        <>
            <Head>
                <title>Login</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={styles.maincontainer}>
                <div className={styles.designcontainer}>
                    <h3 className={styles.heading}>.automateandlearn</h3>
                    <Image src="/images/login-3d.png" className={styles.loginImage} width={500} height={500} alt='login' />
                </div>
                <div className={styles.cardcontainer}>
                    <Logincard />
                </div>
            </div>
        </>
    )
}

export default login