import React, { useEffect, useState } from 'react'
import Head from 'next/head'
import styles from '@/styles/Services.module.css'
import ServiceContents from '@/public/components/serviceContent'
import { useTypewriter, Cursor } from 'react-simple-typewriter'
import Image from 'next/image'
import Link from 'next/link'
import Card from '@/public/components/card'
import { execOnce } from 'next/dist/shared/lib/utils'
import GLOBAL_CONSTANTS from '@/global_constants'
import { useRouter } from 'next/router'

const Services = () => {
  const [text] = useTypewriter({
    words: ServiceContents.titles,
    loop: 0,
  })

  const router = useRouter()

  const openNewWindow = () => {
    const url = `${GLOBAL_CONSTANTS.base_url}/codecompiler`
    if (localStorage.getItem('token')) {
      window.open(url, "CodeEditor")
    } else {
      router.push(`${GLOBAL_CONSTANTS.base_url}/login`)
    }
  }
  return (
    <>
      <Head>
        <title>Services</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.mainContainer}>
        <div className={styles.headContainer}>
          <div className={styles.serviceInfo}>
            <div className={styles.servicetitlecontainer}>
              <div className={styles.serviceheading}>
                <h1>Services</h1>
                Your One Stop Solution To <span className={styles.dynamicText}>{text}</span>
                <Cursor cursorColor='orange' cursorStyle='_' />
              </div>
              <div className={styles.servicedesccontainer}>
                {ServiceContents.description}
              </div>
            </div>
            <div className={styles.imageContainer}>
              <Image className={styles.serviceheadimage} src={ServiceContents.image} width={400} height={400} alt={ServiceContents.titles} />
            </div>
          </div>
        </div>
        <div className={styles.servicesdetails}>
          <h1>Tutorials</h1>
          <p className={styles.tutorialdesc}>
            Explore the world of coding with our diverse range of tutorials covering multiple programming languages. Whether you're a beginner or an experienced coder, our comprehensive guides offer step-by-step instructions and hands-on examples to help you master languages such as Python, JavaScript, HTML/CSS, Java, C++, and more. From understanding the fundamentals to tackling advanced concepts, each tutorial is crafted to enhance your skills and confidence in coding. Dive into our extensive library and embark on a journey to become a proficient programmer, with practical knowledge and expertise at your fingertips.
          </p>
          <Link href={`${GLOBAL_CONSTANTS.base_url}/tutorials`}><button className={styles.btn}>Start Learning &rarr;</button></Link>
        </div>
        <div className={styles.developdetails}>
          <h1>Start Developing</h1>
          <p className={styles.developdesc}>
            Jumpstart your app development journey with our intuitive online code editor, offering support for a wide range of coding languages. Dive into your projects seamlessly and unleash your creativity with ease.
          </p>
          <button onClick={openNewWindow} className={styles.editorbtn}>Open Code Editor &rarr;</button>
        </div>
        <div className={styles.androiddevdetails}>
          <h1>Build Your Dream Android App Today</h1>
          <p className={styles.androiddevelopdesc}>
            Jumpstart your android app development journey with us, offering support for a wide range of coding languages. Dive into your projects seamlessly and unleash your creativity with ease.
          </p>
          <Link href={`${GLOBAL_CONSTANTS.base_url}/androiddev`}><button className={styles.androidbtn}>Build Now &rarr;</button></Link>
        </div>
        <div className={styles.deployappdetails}>
          <div className={styles.plancard}>
            <h1>Start Deploying Today</h1>
            <Card />
          </div>
        </div>
      </div>
    </>
  )
}

export default Services