name: CI-CD via SSH (password)

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install cloudflared
        run: |
          curl -L https://pkg.cloudflare.com/cloudflare-main.gpg | sudo tee /usr/share/keyrings/cloudflare-main.gpg >/dev/null
          echo "deb [signed-by=/usr/share/keyrings/cloudflare-main.gpg] https://pkg.cloudflare.com/cloudflared $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/cloudflared.list
          sudo apt-get update && sudo apt-get install -y cloudflared

      - name: SSH & Run Remote Commands via Cloudflare Tunnel
        run: |
            nohup cloudflared access tcp --hostname ... --url localhost:2222 --service-token-id ... --service-token-secret ... > cloudflared.log 2>&1 &
            echo "Waiting for tunnel to be ready..."
            sleep 5

            ssh -o StrictHostKeyChecking=no -p 2222 ...@localhost <<- 'EOF'
            cd /var/www/automateandlearn
            git pull
            npm install
            npm run build
            pm2 restart automateandlearn
            EOF 
