name: CI-CD via SSH (password)

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install cloudflared
        run: |
          curl -L https://pkg.cloudflare.com/cloudflare-main.gpg | sudo tee /usr/share/keyrings/cloudflare-main.gpg >/dev/null
          echo "deb [signed-by=/usr/share/keyrings/cloudflare-main.gpg] https://pkg.cloudflare.com/cloudflared $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/cloudflared.list
          sudo apt-get update && sudo apt-get install -y cloudflared

      - name: SSH into server via Cloudflare Tunnel (password auth)
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
            mkdir -p ~/.ssh
            chmod 700 ~/.ssh
            cat <<EOF > ~/.ssh/config
            Host myserver
            HostName ${{ secrets.SSH_HOST }}
            User ${{ secrets.SSH_USERNAME }}
            ProxyCommand cloudflared access tcp --hostname ${{ secrets.SSH_HOST }} --url localhost:2222 --service-token-id ${{ secrets.SERVICE_TOKEN_ID }} --service-token-secret ${{ secrets.SERVICE_TOKEN_SECRET }}
            StrictHostKeyChecking no
            EOF
            chmod 600 ~/.ssh/config

      - name: SSH & Run Remote Deploy Commands
        run: ssh myserver -p 2222 "cd /var/www/automateandlearn && git pull && docker-compose up -d npm install && npm run build && pm2 restart automateandlearn" 
